# Generated by Django 2.1.5 on 2019-04-02 18:47

from django.db import migrations
from conf import settings


def insert_sites(apps, schema_editor):
    """Populate the sites model"""
    Site = apps.get_model('sites', 'Site')

    # Register SITE_ID = 1
    Site.objects.update_or_create(pk=settings.SITE_ID, defaults={
        'domain': 'localhost:8000',
        'name': 'default'
    })


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_sites, reverse_code=lambda apps, schema_editor: None)
    ]
